services:
  vote:
    image: lananh03/vote:latest
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8080:80"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - frontend
      - backend
  
  result:
    image: lananh03/result:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:80"
    environment:
      - PORT=${PORT}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DATABASE=${PG_DATABASE}
    networks:
      - frontend
      - backend

  worker:
    image: lananh03/worker:latest
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      - DB_HOST=${PG_HOST}
      - REDIS_HOST=${REDIS_HOST}
      - DB_USER=${PG_USER}
      - DB_PASSWORD=${PG_PASSWORD}
      - DB_DATABASE=${PG_DATABASE}
    networks:
      - backend

  redis:
    image: redis:alpine
    volumes:
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/redis.sh
      interval: 5s
    networks:
      - backend

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"
    networks:
      - backend

volumes:
  db-data:

networks:
  frontend:
  backend: